package com.GG.T9AgeCombat.enums;

public enum LimitationEnum {
    NONE,
    EIGHT_WIDE,
    FIRST_ROUND,
    NOT_LIGHTNING_REFLEXES,
    NOT_GREAT_WEAPON,
    HAND_WEAPON_AND_INFANTRY,
    FIRST_ROUND_NOT_CHARGING,
    FIRST_ROUND_AND_CHARGING,
    TWO_HANDED,
    PASS_DISCIPLINE_TEST;
}
