package com.GG.T9AgeCombat.enums;

public enum ModificationEnum {
    STRENGTH,
    TO_HIT,
    EXTRA_RANKS,
    AGILITY,
    RE_ROLL_TO_HIT,
    RE_ROLL_TO_WOUND,
    ARMOR_PENETRATION,
    ARMOR,
    ATTACKS,
    OFFENSIVE_WEAPON_SKILL,
    WARD_SAVE,
    SUPPORTING_ATTACKS,
    PASS_PANIC_TEST,
    MAGICAL_ATTACKS,
    MOVEMENT_ROLL,
    CANNOT_BE_STOMPED,
    PARRY,
    TWO_HANDED,
    IGNORE_PARRY,
    MOUNTED;
}
