package com.GG.T9AgeCombat.enums;

public enum SpecialRulePropertyEnum {
    BORN_TO_FIGHT,
    LIGHTNING_REFLEXES,
    HORDE,
    SWORD_SWORN,
    HATRED,
    GREAT_WEAPON_STRENGTH,
    GREAT_WEAPON_ARMOR_PENETRATION,
    LIGHTNING_REFLEXES_GREAT_WEAPON,
    STRIKES_LAST,
    LIGHT_ARMOR,
    HEAVY_ARMOR,
    PLATE_ARMOR;
}