package com.GG.T9AgeCombat.enums;

public enum SpecialRulePropertyEnum {
    BORN_TO_FIGHT,
    LIGHTNING_REFLEXES,
    HORDE,
    SWORD_SWORN,
    HATRED,
    GREAT_WEAPON_STRENGTH,
    GREAT_WEAPON_ARMOR_PENETRATION,
    LIGHTNING_REFLEXES_GREAT_WEAPON,
    STRIKES_LAST,
    LIGHT_ARMOR,
    HEAVY_ARMOR,
    PLATE_ARMOR,
    DEVASTATING_CHARGE_LIGHT_LANCE_STRENGTH,
    DEVASTATING_CHARGE_LIGHT_LANCE_ARMOR_PENETRATION,
    EXTRA_ATTACK_1,
    OFFENSIVE_WEAPON_SKILL_1,
    ARMOR_PENETRATION_1,
    AEGIS_5,
    HARNESSED,
    FEARLESS,
    MAGICAL_ATTACKS,
    SWIFTSTRIDE,
    CANNOT_BE_STOMPED,
    MOUNTED;
}